#!/bin/sh

URL="https://127.0.0.1:8081/${SB_API_PREFIX}/access-keys"

curl --insecure -s -o /tmp/access-key "$URL"

jq -r '.accessKeys | .[] | "ID \(.id): \(.accessUrl)"' /tmp/access-key
rm /tmp/access-key